version: '3'

services:
  erlang:
    container_name: erlang
    image: erlang:24.3.4.2
    volumes:
      - ./:/pulsar_client_erl
    depends_on:
      - pulsar
    tty: true

  pulsar:
    container_name: pulsar
    image: streamnative/pulsar:${PULSAR_TAG}
    volumes:
    - ./test/test_SUITE_data/standalone.conf:/pulsar/conf/standalone.conf
    ports:
      - 6650:6650
      - 8080:8080
    restart: always
    command:
      - bin/pulsar
      - standalone

  pulsar-basic-auth:
    container_name: pulsar-basic-auth
    image: streamnative/pulsar:${PULSAR_TAG}
    volumes:
      - ./test/test_SUITE_data/basic_auth:/pulsar/conf/basic_auth:ro
    environment:
      - authenticationEnabled=true
      - authenticationProviders=org.apache.pulsar.broker.authentication.AuthenticationProviderBasic
      - superUserRoles=super
      - brokerClientAuthenticationPlugin=org.apache.pulsar.client.impl.auth.AuthenticationBasic
      - PULSAR_EXTRA_OPTS=-Dpulsar.auth.basic.conf=/pulsar/conf/basic_auth
      - brokerClientAuthenticationParameters={"userId":"super","password":"secretpass"}
    ports:
      - 6651:6650
      - 8081:8080
    restart: always
    # Apparently, function worker seems to interact badly with the
    # authentication config, so we disable it for the tests.
    # https://github.com/apache/pulsar/issues/6309#issuecomment-585498354
    command: >-
      bin/pulsar standalone -nfw -nss

  pulsar-token-auth:
    container_name: pulsar-token-auth
    image: streamnative/pulsar:${PULSAR_TAG}
    volumes:
      - ./test/test_SUITE_data/hs256_secret.key:/pulsar/conf/hs256_secret.key:ro
    environment:
      - authenticationEnabled=true
      - authenticationProviders=org.apache.pulsar.broker.authentication.AuthenticationProviderToken
      - superUserRoles=admin
      - tokenSecretKey=/pulsar/conf/hs256_secret.key
      - brokerClientAuthenticationPlugin=org.apache.pulsar.client.impl.auth.AuthenticationToken
      - brokerClientAuthenticationParameters={"token":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0LXVzZXIifQ.RVPrnEzgEG-iKfpUWKryC39JgWdFXs7MJMUWnHA4ZSg"}
    ports:
      - 6652:6650
      - 8082:8080
    restart: always
    # Apparently, function worker seems to interact badly with the
    # authentication config, so we disable it for the tests.
    # https://github.com/apache/pulsar/issues/6309#issuecomment-585498354
    command: >-
      bin/pulsar standalone -nfw -nss
