version: '3'

services:
  erlang:
    container_name: erlang
    image: erlang:22.3
    volumes:
      - ./:/pulsar_client_erl
#    networks:
#      - emqx_bridge
    depends_on:
      - pulsar
    tty: true

  pulsar:
    container_name: pulsar
    image: apachepulsar/pulsar:${PULSAR_TAG}
    ports:
      - 6650:6650
      - 8080:8080
    restart: always
#    networks:
#      - emqx_bridge
    command:
      - bin/pulsar
      - standalone

#networks:
#  emqx_bridge:
#    driver: bridge
