services:
  erlang:
    container_name: erlang
    image: erlang:26.2.5.2
    volumes:
      - ./:/pulsar_client_erl
    working_dir: /pulsar_client_erl
    depends_on:
      - pulsar
      - toxiproxy
    tty: true

  toxiproxy:
    container_name: toxiproxy
    image: ghcr.io/shopify/toxiproxy
    ports:
      - 8474:8474
      - 7650:6650
    expose:
      - 8474
    volumes:
      - "./.ci/toxiproxy.json:/config/toxiproxy.json"
    restart: always
    command:
      - "-host=0.0.0.0"
      - "-config=/config/toxiproxy.json"

  pulsar:
    container_name: pulsar
    image: apachepulsar/pulsar:${PULSAR_TAG}
    ports:
      - 6650:6650
      - 8081:8080
    restart: always
    command:
      - bash
      - "-c"
      - |
        sed -i '/^advertisedAddress=/advertisedAddress=toxiproxy' conf/standalone.conf
        bin/pulsar standalone -nfw -nss

  pulsar-basic-auth:
    container_name: pulsar-basic-auth
    image: apachepulsar/pulsar:${PULSAR_TAG}
    volumes:
      - ./test/test_SUITE_data/basic_auth:/pulsar/conf/basic_auth:ro
    ports:
      - 6651:6650
      - 8082:8080
    restart: always
    environment:
      - PULSAR_EXTRA_OPTS=-Dpulsar.auth.basic.conf=/pulsar/conf/basic_auth
    # Apparently, function worker seems to interact badly with the
    # authentication config, so we disable it for the tests.
    # https://github.com/apache/pulsar/issues/6309#issuecomment-585498354
    command:
      - bash
      - "-c"
      - |
        sed -i 's#^authenticationEnabled=.*#authenticationEnabled=true#' conf/standalone.conf
        sed -i 's#^authenticationProviders=.*#authenticationProviders=org.apache.pulsar.broker.authentication.AuthenticationProviderBasic#' conf/standalone.conf
        sed -i 's#^superUserRoles=.*#superUserRoles=super#' conf/standalone.conf
        sed -i 's#^brokerClientAuthenticationPlugin=.*#brokerClientAuthenticationPlugin=org.apache.pulsar.client.impl.auth.AuthenticationBasic#' conf/standalone.conf
        sed -i 's#^brokerClientAuthenticationParameters=.*#brokerClientAuthenticationParameters={"userId":"super","password":"secretpass"}#' conf/standalone.conf
        sed -i '/^basicAuthConf=.*/d' conf/standalone.conf
        echo 'basicAuthConf=file:///pulsar/conf/basic_auth' >> conf/standalone.conf
        bin/pulsar standalone -nfw -nss

  pulsar-token-auth:
    container_name: pulsar-token-auth
    image: apachepulsar/pulsar:${PULSAR_TAG}
    volumes:
      - ./test/test_SUITE_data/hs256_secret.key:/pulsar/conf/hs256_secret.key:ro
    ports:
      - 6652:6650
      - 8083:8080
    restart: always
    environment:
      - tokenSecretKey=/pulsar/conf/hs256_secret.key
    # Apparently, function worker seems to interact badly with the
    # authentication config, so we disable it for the tests.
    # https://github.com/apache/pulsar/issues/6309#issuecomment-585498354
    command:
      - bash
      - "-c"
      - |
        sed -i 's#^authenticationEnabled=.*#authenticationEnabled=true#' conf/standalone.conf
        sed -i 's#^authenticationProviders=.*#authenticationProviders=org.apache.pulsar.broker.authentication.AuthenticationProviderToken#' conf/standalone.conf
        sed -i 's#^superUserRoles=.*#superUserRoles=admin#' conf/standalone.conf
        sed -i '/^tokenSecretKey=.*/d' conf/standalone.conf
        echo 'tokenSecretKey=/pulsar/conf/hs256_secret.key' >> conf/standalone.conf
        sed -i 's#^brokerClientAuthenticationPlugin=.*#brokerClientAuthenticationPlugin=org.apache.pulsar.client.impl.auth.AuthenticationToken#' conf/standalone.conf
        # sed -i 's#^brokerClientAuthenticationParameters=.*#brokerClientAuthenticationParameters={"token":"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiJ9.UlVtumfA7z2dSwrtk8Vvt8T_GUiqnfPoHgZWaGcPv051oiR13v-2_oTdYGVwMYbQ56-pM4DocSbc-mSwhh8mhw"}#' conf/standalone.conf
        sed -i 's#^brokerClientAuthenticationParameters=.*#brokerClientAuthenticationParameters=token:eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiJ9.UlVtumfA7z2dSwrtk8Vvt8T_GUiqnfPoHgZWaGcPv051oiR13v-2_oTdYGVwMYbQ56-pM4DocSbc-mSwhh8mhw#' conf/standalone.conf
        bin/pulsar standalone -nfw -nss
