name: Run test cases

on: [push, pull_request]

jobs:
  run_test_cases:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pulsar_tag:
          - 2.7.0
          - 2.9.2.6
    steps:
      - name: install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - uses: actions/checkout@v1
      - name: run test cases
        env:
          PULSAR_TAG: ${{ matrix.pulsar_tag }}
        run: |
          docker-compose -f ./docker-compose.yml up -d
          sleep 3m
          docker exec -i pulsar sh -c "bin/pulsar-admin topics create-partitioned-topic persistent://public/default/test -p 4"
          docker exec -i erlang sh -c "make -C /pulsar_client_erl xref"
          docker exec -i erlang sh -c "make -C /pulsar_client_erl eunit"
          docker exec -i erlang sh -c "make -C /pulsar_client_erl ct"
          docker exec -i erlang sh -c "make -C /pulsar_client_erl cover"
